name: CI - Master

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
            #   - name: Run Tests
            #     run: |
            - name: Set up SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ./deploy.key
                  chmod 600 ./deploy.key
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                  SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
            - name: Build
              run: |
                  npm i
                  npm run build
            - name: Deploy
              run: |
                  scp -i deploy.key -r ./dist/* github@$DEPLOY_TARGET"public/"
              env:
                  DEPLOY_TARGET: ${{secrets.DEPLOY_TARGET}}

              # Or alternately, put this deploy script in your package.json's scripts and run it using yarn/npm:
              # run: yarn deploy
